/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/angleDown.h"
#include "Commands/angleUp.h"
#include "Commands/autoCollector.h"
#include "Commands/autoDriveTrain.h"
#include "Commands/autoElevator.h"
#include "Commands/autoLauncher.h"
#include "Commands/autoShiftToHigh.h"
#include "Commands/autoShiftToLow.h"
#include "Commands/autonomousCommandGroup.h"
#include "Commands/collectFaster.h"
#include "Commands/collectSlower.h"
#include "Commands/compress.h"
#include "Commands/drive.h"
#include "Commands/isRobotReady.h"
#include "Commands/launch.h"
#include "Commands/shift.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveStick = new SmartJoystick(1);
	
	collectSlowerButton = new JoystickButton(driveStick, 7);
	collectSlowerButton->WhileHeld(new collectSlower());
	collectFasterButton = new JoystickButton(driveStick, 8);
	collectFasterButton->WhileHeld(new collectFaster());
	angleDownButton = new JoystickButton(driveStick, 4);
	angleDownButton->WhileHeld(new angleDown());
	angleUpButton = new JoystickButton(driveStick, 6);
	angleUpButton->WhileHeld(new angleUp());
	shiftButton = new JoystickButton(driveStick, 3);
	shiftButton->WhenPressed(new shift());
	lauchBall = new JoystickButton(driveStick, 1);
	lauchBall->WhenPressed(new launch());
	compressButton = new JoystickButton(driveStick, 2);
	compressButton->WhenPressed(new compress());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("autonomousCommandGroup", new autonomousCommandGroup());
	SmartDashboard::PutData("compress", new compress());
	SmartDashboard::PutData("drive", new drive());
	SmartDashboard::PutData("launch", new launch());
	SmartDashboard::PutData("collectFaster", new collectFaster());
	SmartDashboard::PutData("collectSlower", new collectSlower());
	SmartDashboard::PutData("shift", new shift());
	SmartDashboard::PutData("angleUp", new angleUp());
	SmartDashboard::PutData("angleDown", new angleDown());
	SmartDashboard::PutData("isRobotReady", new isRobotReady());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
SmartJoystick* OI::getDriveStick() {
	return driveStick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
