/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartJoystick* throttle;
	SmartJoystick* operatorStick;
	SmartJoystick* driveStick;
	JoystickButton* arcadeDriveButton;
	JoystickButton* collectSlowerButton;
	JoystickButton* collectFasterButton;
	JoystickButton* angleDownButton;
	JoystickButton* angleUpButton;
	JoystickButton* shiftButton;
	JoystickButton* lauchBall;
	JoystickButton* mecanumDriveButton;
	JoystickButton* compressButton;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	SmartJoystick* getDriveStick();
	SmartJoystick* getOperatorStick();
	SmartJoystick* getThrottle();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
