/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SmartGyro* chasisgyro;
	static StallableAnalogEncoder* chasisbatteryCurrent;
	static StallableAnalogEncoder* chasistransducer;
	static SmartCANJaguar* driveTrainfrontLeft;
	static SmartCANJaguar* driveTrainfrontRight;
	static SmartCANJaguar* driveTrainrearLeft;
	static SmartCANJaguar* driveTrainrearRight;
	static RobotDrive* driveTrainRobotDrive;
	static Compressor* driveTrainarmCompressor;
	static Compressor* shiftershifterCompressor;
	static Relay* shiftervalve1;
	static Relay* shiftervalve2;
	static Encoder* shifterQuadratureEncoder1;
	static Encoder* shifterQuadratureEncoder2;
	static Encoder* shifterQuadratureEncoder3;
	static Encoder* shifterQuadratureEncoder4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
