/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	static AnalogChannel* chasisBatteryCurrent;
	static AnalogChannel* chasisPSITransducer120;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SmartCANJaguar* driveTrainFrontLeft;
	static SmartCANJaguar* driveTrainFrontRight;
	static SmartCANJaguar* driveTrainRearLeft;
	static SmartCANJaguar* driveTrainRearRight;
	static RobotDrive* driveTrainRobotDrive;
	static SmartGyro* driveTrainDriveGyro;
	static Encoder* shifterSystemQuadratureEncoder1;
	static Encoder* shifterSystemQuadratureEncoder2;
	static Encoder* shifterSystemQuadratureEncoder3;
	static Encoder* shifterSystemQuadratureEncoder4;
	static Compressor* shifterSystemShifterCompressor;
	static DoubleSolenoid* shifterSystemDoubleSolenoid1;
	static Compressor* launcherArmCompressor;
	static DoubleSolenoid* launcherLauncherSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
