/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
AnalogChannel* RobotMap::chasisBatteryCurrent = NULL;
AnalogChannel* RobotMap::chasisPSITransducer120 = NULL;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SmartCANJaguar* RobotMap::driveTrainFrontLeft = NULL;
SmartCANJaguar* RobotMap::driveTrainFrontRight = NULL;
SmartCANJaguar* RobotMap::driveTrainRearLeft = NULL;
SmartCANJaguar* RobotMap::driveTrainRearRight = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive = NULL;
SmartGyro* RobotMap::driveTrainDriveGyro = NULL;
Compressor* RobotMap::shifterSystemShifterCompressor = NULL;
DoubleSolenoid* RobotMap::shifterSystemDoubleSolenoid1 = NULL;
Compressor* RobotMap::launcherArmCompressor = NULL;
DoubleSolenoid* RobotMap::launcherLauncherSolenoid = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainFrontLeft = new SmartCANJaguar(2);
	
	
	driveTrainFrontRight = new SmartCANJaguar(3);
	
	
	driveTrainRearLeft = new SmartCANJaguar(4);
	
	
	driveTrainRearRight = new SmartCANJaguar(5);
	
	
	driveTrainRobotDrive = new RobotDrive(driveTrainFrontLeft, driveTrainRearLeft,
              driveTrainFrontRight, driveTrainRearRight);
	
	driveTrainRobotDrive->SetSafetyEnabled(false);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);
	driveTrainDriveGyro = new SmartGyro(1, 1);
	lw->AddSensor("Drive Train", "DriveGyro", driveTrainDriveGyro);
	driveTrainDriveGyro->SetSensitivity(0.007);
	shifterSystemShifterCompressor = new Compressor(1, 2, 1, 4);
	
	
	shifterSystemDoubleSolenoid1 = new DoubleSolenoid(1, 1, 2);      
	
	
	launcherArmCompressor = new Compressor(1, 1, 1, 1);
	
	
	launcherLauncherSolenoid = new DoubleSolenoid(1, 3, 4);      
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	chasisBatteryCurrent = new AnalogChannel(1, 2);
	lw->AddSensor("BatteryCurrent",1,2,chasisBatteryCurrent);
		
	chasisPSITransducer120 = new AnalogChannel(1, 3);
	lw->AddSensor("PSITransducer120",1,3,chasisPSITransducer120);
}
