// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	float WilliesSpeed;
	float WilliesSpeed3;
	float mainShooterVoltage;
	float supportShooterVoltage;
	float armVoltage;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* mainShooter;
	DigitalInput* oneBitIREncoder;
	AnalogChannel* angleEncoder;
	SpeedController* angleVictor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Shooter();
	void InitDefaultCommand();
	//void change_speed( float change );
	void ShootTheDisk();
	void SetSpeed(float inSpeed);
	float GetSpeed();
	void ReportSpeed();
	void SetSpeedVic(float vicSpeed);
	float GetSpeedVic();
};
#endif
