/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "angleDown.h"
angleDown::angleDown() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void angleDown::Initialize() {
	Robot::elevator->SetAngleSpeed(Robot::elevator->GetAngleSpeed()-0.50);
}
// Called repeatedly when this Command is scheduled to run
void angleDown::Execute() {
	//Robot::elevator->SetAngleDown();
	RobotMap::elevatorAngleAdjuster->Set(Robot::elevator->GetAngleSpeed());
}
// Make this return true when this Command no longer needs to run execute()
bool angleDown::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void angleDown::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void angleDown::Interrupted() {
}
