/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "angleUp.h"
angleUp::angleUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::collector);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void angleUp::Initialize() {
	Robot::collector->SetAngleSpeed(Robot::collector->GetAngleSpeed()+0.50);
}
// Called repeatedly when this Command is scheduled to run
void angleUp::Execute() {
	//Robot::collector->SetAngleUp();
	RobotMap::collectorCollectorJag->Set(Robot::collector->GetAngleSpeed());
}
// Make this return true when this Command no longer needs to run execute()
bool angleUp::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void angleUp::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void angleUp::Interrupted() {
}
