/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "collectSlower.h"
collectSlower::collectSlower() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void collectSlower::Initialize() {
	Robot::collector->SetLeftSpeed(Robot::collector->GetLeftSpeed()+0.10);
	Robot::collector->SetRightSpeed(Robot::collector->GetRightSpeed()-0.10);
}
// Called repeatedly when this Command is scheduled to run
void collectSlower::Execute() {
	RobotMap::collectorLeftRoller->Set(Robot::collector->GetLeftSpeed());
	RobotMap::collectorRightRoller->Set(Robot::collector->GetRightSpeed());
}
// Make this return true when this Command no longer needs to run execute()
bool collectSlower::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void collectSlower::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void collectSlower::Interrupted() {
}
