/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "driveArcarde.h"
driveArcarde::driveArcarde() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void driveArcarde::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void driveArcarde::Execute() {
	Robot::driveTrain->ArcadeDrive(Robot::oi->getDriveStick());
}
// Make this return true when this Command no longer needs to run execute()
bool driveArcarde::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void driveArcarde::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void driveArcarde::Interrupted() {
}
