/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "sendData.h"
sendData::sendData() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void sendData::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void sendData::Execute() {
	Dashboard &dash = DriverStation::GetInstance()->GetHighPriorityDashboardPacker();
		DriverStation *drive = DriverStation::GetInstance();
		char buffer[1024];
		static int count = 0;
		float battery = drive->GetBatteryVoltage();
		float x =(float) drive->GetStickAxis(1,x);
		float y = (float) drive->GetStickAxis(1,y);
		sprintf(buffer, "%d %f ", count++, battery);
		dash.AddString(buffer);
		dash.Finalize();
}
// Make this return true when this Command no longer needs to run execute()
bool sendData::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void sendData::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void sendData::Interrupted() {
}
