/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "shiftUp.h"
shiftUp::shiftUp() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shifterSystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void shiftUp::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void shiftUp::Execute() {
	Robot::shifterSystem->ShiftDown();
}
// Make this return true when this Command no longer needs to run execute()
bool shiftUp::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void shiftUp::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void shiftUp::Interrupted() {
}
