/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "AirCompressor.h"
#include "../Robotmap.h"
AirCompressor::AirCompressor() : Subsystem("AirCompressor") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	compressor = RobotMap::airCompressorCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	willCompress=2;
}
    
void AirCompressor::InitDefaultCommand() {
	compressor->Stop();
}
void AirCompressor::Compress() {
	if(willCompress%2==0){
		compressor->Start();
	}
	else{
		compressor->Stop();
	}
	willCompress++;
	if(willCompress==1000){
		willCompress=2;
	}
}
