/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef COLLECTOR_H
#define COLLECTOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class Collector: public Subsystem {
private:
	float realSpeed;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Servo* angleAdjuster;
	DigitalInput* highLimit;
	DigitalInput* lowLimit;
	StallableAnalogEncoder* elevationEncoder;
	SpeedController* leftCollect;
	SpeedController* rightCollect;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Collector();
	void InitDefaultCommand();
	void AngleUp();
	void AngleDown();
	void SetSpeed(float speed);
	void ZeroCollector();
	float GetSpeed();
	void SetRealSpeed(float speed);
};
#endif
