/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Collector.h"
#include "../Robotmap.h"
Collector::Collector() : Subsystem("Collector") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftRoller = RobotMap::collectorLeftRoller;
	rightRoller = RobotMap::collectorRightRoller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	realSpeed=0.00;
}
    
void Collector::InitDefaultCommand() {
	leftRoller->Set(0.0);
	rightRoller->Set(0.0);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Collector::SetSpeed(float speed){
	realSpeed=speed;
	leftRoller->Set(realSpeed);
	rightRoller->Set(realSpeed);
}
float Collector::GetSpeed(){
	return realSpeed;
}
