/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Collector.h"
#include "../Robotmap.h"
Collector::Collector() : Subsystem("Collector") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftRoller = RobotMap::collectorLeftRoller;
	rightRoller = RobotMap::collectorRightRoller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	realSpeedLeft=0.00;
	realSpeedRight=0.00;
}
    
void Collector::InitDefaultCommand() {
	leftRoller->Set(0.0);
	rightRoller->Set(0.0);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Collector::SetLeftSpeed(float leftSpeed){
	realSpeedLeft=leftSpeed;
	leftRoller->Set(realSpeedLeft);
}
float Collector::GetLeftSpeed(){
	return realSpeedLeft;
}
void Collector::SetRightSpeed(float rightSpeed){
	realSpeedRight=rightSpeed;
	rightRoller->Set(realSpeedRight);
}
float Collector::GetRightSpeed(){
	return realSpeedRight;
}
