/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class DriveTrain: public Subsystem {
private:
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* frontLeft;
	SmartCANJaguar* frontRight;
	SmartCANJaguar* rearLeft;
	SmartCANJaguar* rearRight;
	RobotDrive* robotDrive;
	Encoder* quadratureEncoder1;
	Encoder* quadratureEncoder2;
	Encoder* quadratureEncoder3;
	Encoder* quadratureEncoder4;
	Relay* spike1;
	Relay* relaySolenoid1;
	Relay* relaySolenoid2;
	Relay* relaySolenoid3;
	Compressor* compressor1;
	DigitalInput* digitalInput1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();
	void InitDefaultCommand();
};
#endif
