/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class DriveTrain: public Subsystem {
private:
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* frontLeft;
	SmartCANJaguar* frontRight;
	SmartCANJaguar* rearLeft;
	SmartCANJaguar* rearRight;
	RobotDrive* robotDrive;
	SmartGyro* driveGyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();
	void InitDefaultCommand();
	void ArcadeDrive(Joystick *stick);
	void MecanumDrive(float joystickX, float joystickY, float joystickTwist);
	string GetDriveMode();
	void ChangeDriveMode();
};
#endif
