/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/drive.h"
const float TWIST_CONSTANT = 0.7f;
const float TWIST_DEADZONE = 0.15f;
const float X_DEADZONE = 0.15f;
const float Y_DEADZONE = 0.15f;
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	gyro = RobotMap::driveTrainGyro;
	rightBack = RobotMap::driveTrainRightBack;
	leftBack = RobotMap::driveTrainLeftBack;
	leftFront = RobotMap::driveTrainLeftFront;
	rightFront = RobotMap::driveTrainRightFront;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	isDriveTrainReady=false;
}
void DriveTrain::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new drive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void DriveTrain::MecanumDrive(float joystickX, float joystickY, float joystickTwist) {
	//add some deadzones
	if(joystickTwist < TWIST_DEADZONE && joystickTwist > -TWIST_DEADZONE){
					joystickTwist = 0.001;
				}
	if(joystickX < X_DEADZONE && joystickX > -X_DEADZONE){
						joystickX = 0.001;
					}
	if(joystickY < Y_DEADZONE && joystickY > -Y_DEADZONE){
						joystickY = 0.001;
					}
	double angle = atan2(joystickX, joystickY);
	float joystickMagnitude = sqrt((joystickX * joystickX) + (joystickY * joystickY));
	float ccTwist = joystickTwist * TWIST_CONSTANT;
	float twist = -joystickTwist * TWIST_CONSTANT;
		
	float leftFrontVal = -1 * (ccTwist + joystickMagnitude*(cos(angle)+sin(angle)));
	float rightFrontVal = (twist + joystickMagnitude*(cos(angle)-sin(angle)));
	float leftBackVal= -1 * (ccTwist + joystickMagnitude*(cos(angle)-sin(angle)));
	float rightBackVal = (twist + joystickMagnitude*(cos(angle)+sin(angle)));
		
	leftFront->Set(leftFrontVal);
	rightFront->Set(rightFrontVal);
	leftBack->Set(leftBackVal);
	rightBack->Set(rightBackVal);
}
void DriveTrain::AutoFoward(){
	leftFront->Set(-0.5);
	rightFront->Set(0.5);
	leftBack->Set(-0.5);
	rightBack->Set(0.5);
	Wait(0.1);
	if((leftFront->Get()==-0.5f)&&(rightFront->Get()==0.5f)
			&&(leftBack->Get()==-0.5f)&&(rightBack->Get()==0.5f))
		isDriveTrainReady=true;
}
void DriveTrain::AutoReverse(){
	leftFront->Set(0.5);
	rightFront->Set(-0.5);
	leftBack->Set(0.5);
	rightBack->Set(-0.5);
}
void DriveTrain::Stop(){
	leftFront->Set(0);
	rightFront->Set(0);
	leftBack->Set(0);
	rightBack->Set(0);
}
bool DriveTrain::isGyroReady(){
	float theAngle = gyro->GetAngle();
	return ((0<theAngle)&&(theAngle<360));
}
