/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class Elevator: public Subsystem {
private:
	float setValue;//declare the value here. it should be private since nothing outside this header and cpp file need to access it.
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* angleAdjuster;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Elevator();
	void InitDefaultCommand();
	void autoDown();
	void autoUp();
	void stopArm();
	bool isAngleAdjusterReady;
	void autoStopArm();
};
#endif
