/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Elevator.h"
#include "../Robotmap.h"
Elevator::Elevator() : Subsystem("Elevator") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	angleAdjuster = RobotMap::elevatorAngleAdjuster;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Elevator::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	angleAdjuster->Set(0.0);
}
void Elevator::autoDown(){
	angleAdjuster->Set(-1);//TODO this value needs to be checked
}
void Elevator::autoUp(){
	angleAdjuster->Set(1);
}
void Elevator::stopArm(){
	if((angleAdjuster->Get()==1)||(angleAdjuster->Get()==-1))
	isAngleAdjusterReady=true;
	angleAdjuster->Set(0);
}
