/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class Elevator: public Subsystem {
private:
	float angleSpeed;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* angleAdjuster;
	StallableAnalogEncoder* elevationEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Elevator();
	void InitDefaultCommand();
	void SetAngleSpeed(float swag);
	float GetAngleSpeed();
	void SetAngleUp();
	void SetAngleDown();
};
#endif
