/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Launcher.h"
#include "../Robotmap.h"
Launcher::Launcher() : Subsystem("Launcher") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	launcherSolenoid1 = RobotMap::launcherLauncherSolenoid1;
	launcherSolenoid2 = RobotMap::launcherLauncherSolenoid2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Launcher::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	launcherSolenoid1->Set(false);
	launcherSolenoid2->Set(false);
}
void Launcher::Launch(){
	launcherSolenoid1->Set(true);
	launcherSolenoid2->Set(true);
	Wait(2.0);
	launcherSolenoid1->Set(false);
	launcherSolenoid2->Set(false);
}
