/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Launcher.h"
#include "../Robotmap.h"
Launcher::Launcher() : Subsystem("Launcher") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	solenoidLeft = RobotMap::launcherSolenoidLeft;
	solenoidRight = RobotMap::launcherSolenoidRight;
	compressor = RobotMap::launcherCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pressureTransducer2 = RobotMap::launcherHighPressureSwitch;
	willCompress=2;
}
    
void Launcher::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	solenoidLeft->Set(false);
	solenoidRight->Set(false);
	compressor->Stop();
}
void Launcher::Launch(){
	solenoidLeft->Set(true);
	solenoidRight->Set(true);
	Wait(1.0);
	solenoidLeft->Set(false);
	solenoidRight->Set(false);
}
void Launcher::Compress() {
	if(willCompress%2==0){
		compressor->Start();
	}
	else{
		compressor->Stop();
	}
	willCompress++;
	if(willCompress==1000){
		willCompress=2;
	}
}
