/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef SHIFTERSYSTEM_H
#define SHIFTERSYSTEM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class ShifterSystem: public Subsystem {
private:
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Compressor* shifterCompressor;
	DoubleSolenoid* shifterSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ShifterSystem();
	void InitDefaultCommand();
	int GetGearSetting();
	void ShiftUp();
	void ShiftDown();
	void Compress();
};
#endif
