/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Shifter.h"
#include "../Robotmap.h"
Shifter::Shifter() : Subsystem("Shifter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	doubleSolenoid = RobotMap::shifterDoubleSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Shifter::InitDefaultCommand() {
	doubleSolenoid->Set(DoubleSolenoid::kOff);
}
void Shifter::Shift(){
	bool changed=false;
	if(doubleSolenoid->Get()==DoubleSolenoid::kOff){
		doubleSolenoid->Set(DoubleSolenoid::kForward);
		changed=true;
	}
	if(doubleSolenoid->Get()==DoubleSolenoid::kForward&&!changed){
		doubleSolenoid->Set(DoubleSolenoid::kReverse);
		changed=true;
	}
	if(doubleSolenoid->Get()==DoubleSolenoid::kReverse&&!changed)
		doubleSolenoid->Set(DoubleSolenoid::kForward);
}
void Shifter::ShiftHigh(){
	doubleSolenoid->Set(DoubleSolenoid::kReverse);
}
void Shifter::ShiftLow(){
	doubleSolenoid->Set(DoubleSolenoid::kForward);
}
bool Shifter::isTheShifterReady(){
	return((doubleSolenoid->Get()==DoubleSolenoid::kForward)||(doubleSolenoid->Get()==DoubleSolenoid::kReverse));
}
