/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Shifter.h"
#include "../Robotmap.h"
#include "../Commands/compressShifter.h"
Shifter::Shifter() : Subsystem("Shifter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shifterCompressor = RobotMap::shiftershifterCompressor;
	valve1 = RobotMap::shiftervalve1;
	valve2 = RobotMap::shiftervalve2;
	quadratureEncoder1 = RobotMap::shifterQuadratureEncoder1;
	quadratureEncoder2 = RobotMap::shifterQuadratureEncoder2;
	quadratureEncoder3 = RobotMap::shifterQuadratureEncoder3;
	quadratureEncoder4 = RobotMap::shifterQuadratureEncoder4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Shifter::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new compressShifter());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
