// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public Subsystem {
private:
	
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* leftDrive;
	CANJaguar* rightDrive;
	RobotDrive* robotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	float encoder1;
	float encoder2;
	float voltage1;
	float voltage2;
	float voltage3;
	float voltage4;
	DriveTrain();
	void InitDefaultCommand();
	void Drive_with_joy( Joystick *stick );
	void Drive_with_abandon( void );
	void Halt_drive( void );
	void ReportEncoders ();
	//void ConfigureJaguarEncoder(CANJaguar* cANJaguar1, CANJaguar* cANJaguar2);
};
#endif
