// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Shooter.h"
#include "../Robotmap.h"
#include "../Commands/ShooterSensors.h"
Shooter::Shooter() : Subsystem("Shooter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	mainShooter = RobotMap::shootermainShooter;
	oneBitIREncoder = RobotMap::shooteroneBitIREncoder;
	angleEncoder = RobotMap::shooterAngleEncoder;
	angleVictor = RobotMap::shooterAngleVictor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	WilliesSpeed = 0.00;
	WilliesSpeed3 = 0.00;
}
    
void Shooter::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	//mainShooter->ChangeControlMode(CANJaguar::kPosition);
	mainShooter->SetPositionReference(CANJaguar::kPosRef_QuadEncoder);
	mainShooter->ConfigEncoderCodesPerRev(360);
	mainShooter->EnableControl();
	//printf ("the configuration for SHOOTAH is complete\n");
	RobotMap::shootermainShooter->Set(WilliesSpeed);
	//printf ("speeding at... %f\n", WilliesSpeed);
	//printf ("angeling at... %f\n", WilliesSpeed3);
	//printf ("This is the LATEST changed build as of 10/19/13\n");
	printf ("Some features of SHOOTER have been disabled\n");
	RobotMap::shooterAngleVictor->Set(WilliesSpeed3);
	SetDefaultCommand(new ShooterSensors());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
/*void Shooter::ShootTheDisk() {
	
	//Robot::shooter->ShootTheDisk();
	RobotMap::shootermainShooter->Set(WilliesSpeed);
}
*/
void Shooter::SetSpeed(float inSpeed)
{
	WilliesSpeed = inSpeed;
	
	mainShooter->Set( WilliesSpeed );
	
}
float Shooter::GetSpeed()
{
	return ( WilliesSpeed );
}
void Shooter::ReportSpeed()
{
	double encoderSpeed1 = mainShooter->GetPosition();
	//int lightInfo = oneBitIREncoder->Get();
	//float analogEncoder = angleEncoder->GetVoltage();
	float mainShooterVoltage = mainShooter->GetOutputVoltage();
	//float armVoltage = angleVictor->Get();
	SmartDashboard::PutNumber("shooter encoder 1", (double) encoderSpeed1);
	//SmartDashboard::PutNumber("light is", lightInfo);
	//SmartDashboard::PutNumber("arm encoder", (double)analogEncoder);
	//SmartDashboard::PutNumber("shooter set", (double)WilliesSpeed);
	//SmartDashboard::PutNumber("angleing set", (double)WilliesSpeed3);
	SmartDashboard::PutNumber("main shooter voltage", (double)mainShooterVoltage);
	//SmartDashboard::PutNumber("angle victor voltage", (double)armVoltage);
	//printf ("reproting...");
}
void Shooter::SetSpeedVic(float vicSpeed)
{
	WilliesSpeed3 = vicSpeed;
	angleVictor->Set( WilliesSpeed3 );
}
float Shooter::GetSpeedVic()
{
	return ( WilliesSpeed3 );
}
